### ISSUE TITLE
Automatic page flipping is not supported

### ISSUE THREAD

**Issue by ssrpanel** [Ayesh/InstagramDownload#8]
Automatic page flipping is not supported

**Comment by Ayesh** [comment]
This library uses meta tags to determine the full URL to the image. This attribute does not get the rest of the images by definition.  The reason why we use meta tags is because it is quite solid. For all the years that this library has been active, we never needed to change the parser to keep up with Instagram.

Unless a significant contribution is coming towards the library, I do not have any plans to use a possibly fragile alternative parser to get all images/videos from a paged post.
